name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup branch (main)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: dxara10
          outputs: dist/snake.svg

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake animation"
          file_pattern: dist/snake.svg
